// Declarative action configuration per screen
// Supported param types: text, number, dropdown, dropdown-api, toggle

const actions = {
    rdm: {
        create: {
            label: 'Create RDM',
            api: 'kpr',
            endpoint: '/rdm/create',
            params: [
                {
                    name: 'vc',
                    label: 'vCenter',
                    type: 'dropdown-api',
                    source: '/vcenters',
                    required: true,
                    prefillFrom: ['vc', 'vcenter'],
                },
                {
                    name: 'esxCluster',
                    label: 'ESX Cluster',
                    type: 'dropdown-api',
                    source: '/esx-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['esx_cluster', 'cluster'],
                },
                {
                    name: 'dsCluster',
                    label: 'DS Cluster',
                    type: 'dropdown-api',
                    source: '/ds-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['ds_cluster', 'cluster'],
                },
                {
                    name: 'oracleName',
                    label: 'Oracle Name',
                    type: 'text',
                    required: true,
                    prefillFrom: 'name',
                },
                { name: 'dataAmount', label: 'Data Amount', type: 'number', required: true, min: 1, max: 128 },
                { name: 'dataSize', label: 'Data Size (GB)', type: 'number', required: true, min: 1, max: 50000 },
                { name: 'recAmount', label: 'REC Amount', type: 'number', required: true, min: 1, max: 128 },
                { name: 'recSize', label: 'REC Size (GB)', type: 'number', required: true, min: 1, max: 50000 },
                { name: 'crsAmount', label: 'CRS Amount', type: 'number', required: true, min: 1, max: 128 },
                { name: 'crsSize', label: 'CRS Size (GB)', type: 'number', required: true, min: 1, max: 50000 },
            ],
        },
        delete: {
            label: 'Delete RDM',
            api: 'kpr',
            endpoint: '/rdm/delete',
            params: [
                {
                    name: 'vc',
                    label: 'vCenter',
                    type: 'dropdown-api',
                    source: '/vcenters',
                    required: true,
                    prefillFrom: ['vc', 'vcenter'],
                },
                {
                    name: 'esxCluster',
                    label: 'ESX Cluster',
                    type: 'dropdown-api',
                    source: '/esx-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['esx_cluster', 'cluster'],
                },
                {
                    name: 'naas',
                    label: 'NAA List',
                    type: 'dropdown-api',
                    source: '/rdms/by-vc-cluster',
                    dependsOn: ['vc', 'esxCluster'],
                    query: { vc: 'vc', esx_cluster: 'esxCluster' },
                    required: true,
                    multi: true,
                    prefillFrom: ['naa', 'name'],
                    prefillMode: 'list',
                },
            ],
        },
    },

    ds: {
        create: {
            label: 'Create Datastore',
            api: 'kpr',
            endpoint: '/ds/create',
            params: [
                {
                    name: 'vc',
                    label: 'vCenter',
                    type: 'dropdown-api',
                    source: '/vcenters',
                    required: true,
                    prefillFrom: ['vc', 'vcenter'],
                },
                {
                    name: 'dsCluster',
                    label: 'DS Cluster',
                    type: 'dropdown-api',
                    source: '/ds-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['ds_cluster', 'cluster'],
                },
                {
                    name: 'esxCluster',
                    label: 'ESX Cluster',
                    type: 'dropdown-api',
                    source: '/esx-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['esx_cluster', 'cluster'],
                },
                { name: 'amount', label: 'Amount', type: 'number', required: true, min: 1, max: 1000 },
            ],
        },
        delete: {
            label: 'Remove Datastore',
            api: 'kpr',
            endpoint: '/ds/delete',
            params: [
                {
                    name: 'vc',
                    label: 'vCenter',
                    type: 'dropdown-api',
                    source: '/vcenters',
                    required: true,
                    prefillFrom: ['vc', 'vcenter'],
                },
                {
                    name: 'dsCluster',
                    label: 'DS Cluster',
                    type: 'dropdown-api',
                    source: '/ds-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['ds_cluster', 'cluster'],
                },
                {
                    name: 'dsNames',
                    label: 'Datastores',
                    type: 'dropdown-api',
                    source: '/datastores/by-vc-cluster',
                    dependsOn: ['vc', 'dsCluster'],
                    query: { vc: 'vc', ds_cluster: 'dsCluster' },
                    required: true,
                    multi: true,
                    prefillFrom: 'name',
                    prefillMode: 'list',
                },
            ],
        },
        createCluster: {
            label: 'Create DS Cluster',
            api: 'kpr',
            endpoint: '/ds/cluster/create',
            endpointSelector: 'clusterType',
            endpointByValue: {
                netapp: '/ds/cluster/netapp/create',
                vmax: '/ds/cluster/vmax/create',
                pflex: '/ds/cluster/pflex/create',
            },
            params: [
                {
                    name: 'vc',
                    label: 'vCenter',
                    type: 'dropdown-api',
                    source: '/vcenters',
                    required: true,
                    prefillFrom: ['vc', 'vcenter'],
                },
                {
                    name: 'clusterType',
                    label: 'Cluster Type',
                    type: 'dropdown',
                    options: [
                        { value: 'netapp', label: 'NetApp' },
                        { value: 'vmax', label: 'VMAX' },
                        { value: 'pflex', label: 'PFlex' },
                    ],
                    required: true,
                },
                { name: 'clusterName', label: 'Cluster Name', type: 'text', required: true },
                {
                    name: 'svm',
                    label: 'SVM',
                    type: 'text',
                    required: true,
                    visibleWhen: { field: 'clusterType', equals: 'netapp' },
                },
                {
                    name: 'aggregate',
                    label: 'Aggregate',
                    type: 'dropdown-api',
                    source: '/aggregates',
                    required: true,
                    visibleWhen: { field: 'clusterType', equals: 'netapp' },
                },
                {
                    name: 'storageGroup',
                    label: 'Storage Group',
                    type: 'text',
                    required: true,
                    visibleWhen: { field: 'clusterType', equals: 'vmax' },
                },
                {
                    name: 'serviceLevel',
                    label: 'Service Level',
                    type: 'dropdown',
                    options: ['Diamond', 'Platinum', 'Gold'],
                    required: true,
                    visibleWhen: { field: 'clusterType', equals: 'vmax' },
                },
                {
                    name: 'protectionDomain',
                    label: 'Protection Domain',
                    type: 'text',
                    required: true,
                    visibleWhen: { field: 'clusterType', equals: 'pflex' },
                },
                {
                    name: 'replicationFactor',
                    label: 'Replication Factor',
                    type: 'number',
                    required: true,
                    min: 1,
                    max: 4,
                    visibleWhen: { field: 'clusterType', equals: 'pflex' },
                },
            ],
        },
    },

    esx: {
        create: {
            label: 'Add ESX Host',
            api: 'kpr',
            endpoint: '/esx/host/add',
            params: [
                {
                    name: 'vc',
                    label: 'vCenter',
                    type: 'dropdown-api',
                    source: '/vcenters',
                    required: true,
                    prefillFrom: ['vc', 'vcenter'],
                },
                {
                    name: 'originalEsxCluster',
                    label: 'Original ESX Cluster',
                    type: 'dropdown-api',
                    source: '/esx-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['esx_cluster', 'cluster'],
                },
                {
                    name: 'targetEsxCluster',
                    label: 'Target ESX Cluster',
                    type: 'dropdown-api',
                    source: '/esx-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['esx_cluster', 'cluster'],
                },
                {
                    name: 'esxNames',
                    label: 'ESX Names',
                    type: 'dropdown-api',
                    source: '/esx/by-vc-cluster',
                    dependsOn: ['vc', 'originalEsxCluster'],
                    query: { vc: 'vc', esx_cluster: 'originalEsxCluster' },
                    required: true,
                    multi: true,
                    prefillFrom: 'name',
                    prefillMode: 'list',
                },
            ],
        },
        delete: {
            label: 'Remove ESX Host',
            api: 'kpr',
            endpoint: '/esx/host/remove',
            params: [
                {
                    name: 'vc',
                    label: 'vCenter',
                    type: 'dropdown-api',
                    source: '/vcenters',
                    required: true,
                    prefillFrom: ['vc', 'vcenter'],
                },
                {
                    name: 'dsCluster',
                    label: 'DS Cluster',
                    type: 'dropdown-api',
                    source: '/ds-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['ds_cluster', 'cluster'],
                },
                {
                    name: 'esxCluster',
                    label: 'ESX Cluster',
                    type: 'dropdown-api',
                    source: '/esx-clusters/by-vc',
                    dependsOn: 'vc',
                    queryKey: 'vc',
                    required: true,
                    prefillFrom: ['esx_cluster', 'cluster'],
                },
                {
                    name: 'esxNames',
                    label: 'ESX Names',
                    type: 'dropdown-api',
                    source: '/esx/by-vc-cluster',
                    dependsOn: ['vc', 'esxCluster'],
                    query: { vc: 'vc', esx_cluster: 'esxCluster' },
                    required: true,
                    multi: true,
                    prefillFrom: 'name',
                    prefillMode: 'list',
                },
            ],
        },
        createCluster: {
            label: 'Add ESX Cluster',
            api: 'kpr',
            endpoint: '/esx/cluster/create',
            endpointSelector: 'clusterType',
            endpointByValue: {
                netapp: '/esx/cluster/netapp/create',
                vmax: '/esx/cluster/vmax/create',
                pflex: '/esx/cluster/pflex/create',
            },
            params: [
                {
                    name: 'vc',
                    label: 'vCenter',
                    type: 'dropdown-api',
                    source: '/vcenters',
                    required: true,
                    prefillFrom: ['vc', 'vcenter'],
                },
                {
                    name: 'clusterType',
                    label: 'Cluster Type',
                    type: 'dropdown',
                    options: [
                        { value: 'netapp', label: 'NetApp' },
                        { value: 'vmax', label: 'VMAX' },
                        { value: 'pflex', label: 'PFlex' },
                    ],
                    required: true,
                },
                { name: 'clusterName', label: 'Cluster Name', type: 'text', required: true },
                {
                    name: 'managementVlan',
                    label: 'Management VLAN',
                    type: 'number',
                    required: true,
                    min: 1,
                    max: 4094,
                    visibleWhen: { field: 'clusterType', equals: 'netapp' },
                },
                {
                    name: 'hostCount',
                    label: 'Host Count',
                    type: 'number',
                    required: true,
                    min: 1,
                    max: 64,
                    visibleWhen: { field: 'clusterType', in: ['netapp', 'pflex'] },
                },
                {
                    name: 'fabricA',
                    label: 'Fabric A',
                    type: 'text',
                    required: true,
                    visibleWhen: { field: 'clusterType', equals: 'vmax' },
                },
                {
                    name: 'fabricB',
                    label: 'Fabric B',
                    type: 'text',
                    required: true,
                    visibleWhen: { field: 'clusterType', equals: 'vmax' },
                },
                {
                    name: 'sdsDomain',
                    label: 'SDS Domain',
                    type: 'text',
                    required: true,
                    visibleWhen: { field: 'clusterType', equals: 'pflex' },
                },
            ],
        },
    },

    exch: {
        create: {
            label: 'Create Volume',
            api: 'exch',
            endpoint: '/volume/create',
            params: [
                { name: 'volumeName', label: 'Volume Name', type: 'text', required: true },
                { name: 'aggregate', label: 'Aggregate', type: 'dropdown-api', source: '/aggregates', required: true },
                { name: 'size', label: 'Size (GB)', type: 'number', required: true, min: 1, max: 50000 },
                { name: 'protocol', label: 'Protocol', type: 'dropdown', options: ['NFS', 'CIFS', 'iSCSI', 'FC'], required: true },
                { name: 'exportPolicy', label: 'Export Policy', type: 'text', required: false },
            ],
        },
        delete: {
            label: 'Delete Volume',
            api: 'exch',
            endpoint: '/volume/delete',
            params: [
                { name: 'volumeName', label: 'Volume', type: 'dropdown-api', source: '/volumes', required: true, multi: true },
                { name: 'confirm', label: 'Confirm Deletion', type: 'toggle', required: true },
            ],
        },
        extend: {
            label: 'Extend Volume',
            api: 'exch',
            endpoint: '/volume/extend',
            params: [
                { name: 'volumeName', label: 'Volume', type: 'dropdown-api', source: '/volumes', required: true },
                { name: 'additionalSize', label: 'Additional Size (GB)', type: 'number', required: true, min: 1 },
            ],
        },
    },

    qtree: {
        create: {
            label: 'Create QTree',
            api: 'kpr',
            endpoint: '/qtree/create',
            params: [
                { name: 'qtreeName', label: 'QTree Name', type: 'text', required: true },
                { name: 'volume', label: 'Volume', type: 'dropdown-api', source: '/volumes', required: true },
                { name: 'securityStyle', label: 'Security Style', type: 'dropdown', options: ['unix', 'ntfs', 'mixed'], required: true },
                { name: 'exportPolicy', label: 'Export Policy', type: 'text', required: false },
            ],
        },
        delete: {
            label: 'Delete QTree',
            api: 'kpr',
            endpoint: '/qtree/delete',
            params: [
                { name: 'qtreeName', label: 'QTree', type: 'dropdown-api', source: '/qtrees', required: true, multi: true },
                { name: 'confirm', label: 'Confirm Deletion', type: 'toggle', required: true },
            ],
        },
        extend: {
            label: 'Extend QTree',
            api: 'kpr',
            endpoint: '/qtree/extend',
            params: [
                { name: 'qtreeName', label: 'QTree', type: 'dropdown-api', source: '/qtrees', required: true },
                { name: 'additionalSize', label: 'Additional Size (GB)', type: 'number', required: true, min: 1 },
            ],
        },
    },
};

export default actions;

export function getActionsForScreen(screenId) {
    return actions[screenId] || {};
}
