import { dsClusterParam, esxClusterParam, networkParam, vcenterParam } from './shared';

const dsActions = {
    create: {
        label: 'Create Datastore',
        api: 'kpr',
        method: 'post',
        endpoint: '/datastore',
        params: [
            networkParam,
            vcenterParam,
            dsClusterParam,
            esxClusterParam,
            { name: 'amount', label: 'Amount', type: 'number', required: true, min: 1, max: 1000 },
        ],
    },
    delete: {
        label: 'Remove Datastore',
        api: 'kpr',
        method: 'delete',
        endpoint: '/datastore',
        params: [
            networkParam,
            vcenterParam,
            {
                name: 'cluster_name',
                label: 'DS Cluster',
                type: 'dropdown-api',
                sourceApi: 'kpr',
                source: '/network/{network}/vcenter/{vc_name}/ds_clusters',
                dependsOn: ['network', 'vc_name'],
                required: true,
                prefillFrom: ['ds_cluster', 'cluster'],
            },
            {
                name: 'ds_names',
                label: 'Datastores',
                type: 'dropdown-api',
                sourceApi: 'kpr',
                source: '/network/{network}/vcenter/{vc_name}/cluster/{cluster_name}/datastores',
                dependsOn: ['network', 'vc_name', 'cluster_name'],
                required: true,
                multi: true,
                prefillFrom: 'name',
                prefillMode: 'list',
            },
        ],
    },
    createCluster: {
        label: 'Create DS Cluster',
        api: 'kpr',
        method: 'post',
        endpoint: '/ds_cluster/ontap',
        endpointSelector: 'clusterType',
        endpointByValue: {
            netapp: '/ds_cluster/ontap',
            vmax: '/ds_cluster/vmax',
            pflex: '/ds_cluster/pflex',
        },
        params: [
            networkParam,
            vcenterParam,
            {
                name: 'clusterType',
                label: 'Cluster Type',
                type: 'dropdown',
                options: [
                    { value: 'netapp', label: 'NetApp' },
                    { value: 'vmax', label: 'VMAX' },
                    { value: 'pflex', label: 'PFlex' },
                ],
                required: true,
                send: false,
            },
            { name: 'cluster_name', label: 'Cluster Name', type: 'text', required: true },
            { name: 'size', label: 'Size In TB', type: 'text', required: true },
            { name: 'amount', label: 'Amount Of Ds', type: 'text', required: true },
            {
                name: 'svm',
                label: 'SVM',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'netapp' },
            },
            {
                name: 'target_fcalias',
                label: 'Target Fcalias',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', in: ['netapp', 'vmax'] },
            },
            {
                name: 'storage_array_ip',
                label: 'Storage Array Ip',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'netapp' },
            },
            {
                name: 'node_name',
                label: 'Node Name',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'netapp' },
            },
            {
                name: 'unisphere_ip',
                label: 'Unisphere Ip',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'vmax' },
            },
            {
                name: 'sid',
                label: 'Sid Of Vmax',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'vmax' },
            },
            {
                name: 'pg_name',
                label: 'PG Name',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'vmax' },
            },
        ],
    },
};

export default dsActions;
