import { dsClusterParam, esxClusterParam, networkParam, vcenterParam } from './shared';

const esxActions = {
    create: {
        label: 'Add ESX Host',
        api: 'kpr',
        method: 'put',
        endpoint: '/zoner/hosts',
        params: [
            networkParam,
            vcenterParam,
            dsClusterParam,
            {
                name: 'esx_cluster_name',
                label: 'ESX Cluster',
                type: 'dropdown-api',
                sourceApi: 'kpr',
                source: '/network/{network}/vcenter/{vc_name}/clusters',
                dependsOn: ['network', 'vc_name'],
                required: true,
                prefillFrom: ['esx_cluster', 'cluster'],
            },
            {
                name: 'original_esx_cluster',
                label: 'Original ESX Cluster',
                type: 'dropdown-api',
                sourceApi: 'kpr',
                source: '/network/{network}/vcenter/{vc_name}/clusters',
                dependsOn: ['network', 'vc_name'],
                required: true,
                send: false,
                prefillFrom: ['esx_cluster', 'cluster'],
            },
            {
                name: 'hosts',
                label: 'ESX Names',
                type: 'dropdown-api',
                sourceApi: 'kpr',
                source: '/network/{network}/vcenter/{vc_name}/cluster/{original_esx_cluster}/hosts',
                dependsOn: ['network', 'vc_name', 'original_esx_cluster'],
                required: true,
                multi: true,
                prefillFrom: 'name',
                prefillMode: 'list',
            },
        ],
    },
    delete: {
        label: 'Remove ESX Host',
        api: 'kpr',
        method: 'delete',
        endpoint: '/zoner/hosts',
        params: [
            networkParam,
            vcenterParam,
            {
                name: 'esx_cluster_name',
                label: 'ESX Cluster',
                type: 'dropdown-api',
                sourceApi: 'kpr',
                source: '/network/{network}/vcenter/{vc_name}/clusters',
                dependsOn: ['network', 'vc_name'],
                required: true,
                prefillFrom: ['esx_cluster', 'cluster'],
            },
            {
                name: 'hosts',
                label: 'ESX Names',
                type: 'dropdown-api',
                sourceApi: 'kpr',
                source: '/network/{network}/vcenter/{vc_name}/cluster/{esx_cluster_name}/hosts',
                dependsOn: ['network', 'vc_name', 'esx_cluster_name'],
                required: true,
                multi: true,
                prefillFrom: 'name',
                prefillMode: 'list',
            },
        ],
    },
    createCluster: {
        label: 'Add ESX Cluster',
        api: 'kpr',
        method: 'post',
        endpoint: '/zoner/ontap/cluster',
        endpointSelector: 'clusterType',
        endpointByValue: {
            netapp: '/zoner/ontap/cluster',
            vmax: '/zoner/vmax/cluster',
        },
        params: [
            networkParam,
            vcenterParam,
            {
                name: 'clusterType',
                label: 'Cluster Type',
                type: 'dropdown',
                options: [
                    { value: 'netapp', label: 'NetApp' },
                    { value: 'vmax', label: 'VMAX' },
                ],
                required: true,
                send: false,
            },
            esxClusterParam,
            {
                name: 'svm',
                label: 'SVM',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'netapp' },
            },
            {
                name: 'ontap_ip',
                label: 'Ontap Ip',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'netapp' },
            },
            {
                name: 'unisphere_ip',
                label: 'Unisphere Ip',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'vmax' },
            },
            {
                name: 'sid',
                label: 'Sid',
                type: 'text',
                required: true,
                visibleWhen: { field: 'clusterType', equals: 'vmax' },
            },
            {
                name: 'target_fcalias',
                label: 'Target Fcalias',
                type: 'text',
                required: true,
            },
        ],
    },
};

export default esxActions;
